### ISSUE TITLE
Performance issue on large files

### ISSUE THREAD

**Issue by thery** [coq-community/vscoq#116]
The interface seems less reactive when working on a large file.
For example the file [CPoly_I.v](https://github.com/FlorianSteinberg/Cheby/blob/master/CPoly_I.v) has more than 3000 lines and inserting and executing
```
Goal True -> True -> True.
intros H1.
intros H2.
exact H1.
Qed.
```
at the beginning of the file takes ages.
It seems that at every execution, the ```outline``` window indicates ``` Loading document symbols for CPoly_I.v``` than after a while ```No symbol found for document CPoly_I.v```

**Comment by fakusb** [comment]
I think the problem is that whenever a sentence (the thing terminated by ". ") is `inserted`, the whole document gets re-parsed and  the language server forgets that it could just "shift" all sentences by one.
There is logic in the source that should shift, but apparently it does not shift.

If anyone has any insights on this problem, please speak here :)

**Comment by thery** [comment]
@fakusb Thanks!
