### ISSUE TITLE
CoqIDE-like view

### ISSUE THREAD

**Issue by orilahav** [coq-community/vscoq#154]
Feature request (unless somehow possible and I couldn't see how):
I like CoqIDE's default split where the queries and messages are shown below the ProofView.

Is it possible to get such view in vscoq?

I understand that vscode "problem/output/..." pane cannot be simply set in such position.

**Comment by paldepind** [comment]
I don't think that is possible due to limitations in VSCode's panel-thing. It can be shown at the bottom/left/right but will have to take up an entire side.

One solution would be for vscoq to show the output from Coq in the bottom of the ProofView. That should be possible since the proof view is created with HTML.

**Comment by SohnyBohny** [comment]
Also colored output (like CoqIDE) would be nice :rainbow:

**Comment by rtetley** [comment]
This is done in VsCoq 2
