### ISSUE TITLE
freshness of universes

### ISSUE THREAD

**Issue by gares** [coq-community/vscoq#206]
In the STM universe levels are always allocated in master via the remote counter API, this requires master/workers to chit chat all the time.

It would be much simpler to have freshness be enforced by the universe name which could be `Module.proof_name.$N` (or even `Module.$fresh.$N`) so that workers for proofs (or tactics a la "par: ") can allocate universes in their corners and have no clash.

This change has to be made in Coq (assuming it is possible) CC @skyskimmer

**Comment by SkySkimmer** [comment]
Depending on the proof name doesn't work for `par:` since it's all one proof.

Also the proof name is questionable when we run tactics and not necessarily unique, eg
~~~coq
Goal Type.
bla.
Save foo.
Goal Type.
bli.
Qed.
~~~
I think bla and bli get the same Unnamed_thm name.

I feel like we have some related issue on the Coq side but couldn't find it with a quick search.

**Comment by gares** [comment]
Ok, my solution is not good enough. But do you think we can come up with something like that? I mean, we can find a way to get a unique ID per "job", be it a full proof or a tactic. What about the rest of Coq?

**Comment by SkySkimmer** [comment]
Closed by https://github.com/coq/coq/pull/14050
