### ISSUE TITLE
ProofView "Not in proof mode." text is black on black using default settings

### ISSUE THREAD

**Issue by carlpaten** [coq-community/vscoq#289]
Ubuntu 21.10
VS Code 1.65.2, theme "Dark+ (default dark)"
VSCoq v0.3.6
Coq Platform 2022.03.0, installed via `snap`
All style settings are out-of-the-box defaults

![image](https://user-images.githubusercontent.com/1834919/159798159-12e52f96-9d0d-4e4f-bdac-1722fa82f43a.png)

**Comment by david-masters** [comment]
I had this problem too right after I installed vscoq, but restarting code fixed it for me.

**Comment by thery** [comment]
is this still an issue?

**Comment by palmskog** [comment]
According to a [report on Zulip](https://coq.zulipchat.com/#narrow/stream/237662-VsCoq-devs-.26-users/topic/.E2.9C.94.20ProofView.20black.20text.20dark.20background/near/317195609), this issue still persists.

**Comment by 4ever2** [comment]
This can be reproduced reliably with VsCoq v0.3.6 by:
1) Set VSCode theme to any dark theme
2) Uninstall VsCoq
3) Completely close all running VSCode windows
4) Reopen and reinstall
5) Load proof view for any Coq file

The problem is that the `--vscode-coq-proofviewText` CSS variable doesn't exist when opening a webview just after installing the extension. However, after restarting VSCode the variable exists when opening webviews.
This is hard to debug since the same behaviour cannot be observed when installing from a locally built 
vsix file. It only happens when installing the extension from the marketplace.

This seems like a bug in VSCode, but it is hard to say for sure since I cannot debug it.

**Comment by rtetley** [comment]
This is functional in VsCoq 2
