### ISSUE TITLE
Inconsistent Colorization When Stepping Over Proofs

### ISSUE THREAD

**Issue by ArktisDev** [coq-community/vscoq#293]
I recently started learning COQ and I am incredibly confused with the inconsistent colorization when stepping over proofs.

For example when stepping over each part of the proof until all subgoals are completed, and then stepping over the QED, the colorization ends up looking like this:
<img width="272" alt="Screen Shot 2022-04-12 at 12 23 15" src="https://user-images.githubusercontent.com/66231124/163019177-589faecf-bd39-47c5-835b-b065350dda4f.png">

However, if I start before opening the proof and I step over the entire proof all at once, the colorization ends up looking like this:
<img width="284" alt="Screen Shot 2022-04-12 at 12 24 32" src="https://user-images.githubusercontent.com/66231124/163019297-07367c34-1322-4a92-ac59-5c14fbf90bfc.png">

I was searching for hours online why this is happening, and I found some discussion about this being similar to the CoqIDE colorization mechanics, but I honestly have no idea about any of that.

Can someone explain why the colorization is acting like this and what it means?

**Comment by TheoWinterhalter** [comment]
It is describing two states. The green is what has been fully checked, while purple is only staged to be checked at a later stage when the CPU is available I think.

**Comment by ArktisDev** [comment]
In my case, the purple is never going away and the CPU is certainly free though. Why is it never clearing the purple?

**Comment by gares** [comment]
In CoqIDE there is an explicit button to check, in the master process, all the proofs generated by workers. Then the color changes. Since we plan to get rid of this detail, I think this issue was already marked as wontfix elsewhere.

In general, if you step by step, then it is master doing all the work, while if you jump over, it may delegate the proofs to the workers. Workers lack a global understanding of universe constraints, so they only check that the proof is OK is isolation, not that it fits well in the entire context.

**Comment by ArktisDev** [comment]
I see, that makes sense. Thanks for clarifying.

**Comment by Zimmi48** [comment]
Without waiting for the new document manager, I would suggest getting rid of this different color and just making the thing green. It's not the first time I've seen this behavior confused beginners. I've also been asked about it by students.
