### ISSUE TITLE
Detection of coq's binary & lib paths

### ISSUE THREAD

**Issue by maximedenes** [coq-community/vscoq#361]
When the corresponding settings are not set explicitly, we should look for Coq and its libraries in standard places (corresponding to the various standard means of installation). A popup explaining that we made a guess would be nice, at least the first time we do it.

**Comment by gares** [comment]
I started looking into this.

A first cleanup on the coq side is to be able to query `vscoqtop` and see if it is usable.
I believe it is nice to tell the user "this is what I found in the path, but it does not work because of $MSG" upfront.

Calling coq with `-where` was no enough, while after https://github.com/coq/coq/pull/17317 it is.
