### ISSUE TITLE
[vscoq2] incompatible with vim extension

### ISSUE THREAD

**Issue by ccyip** [coq-community/vscoq#645]
I am using [VSCodeVim](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim) for vim keymap. This is the most popular vim emulation extension for vscode, so I reckon there are at least a dozen of vscoq users with this extension installed.

The issue is that the goal view is not updated when I navigate the proofs. For example, if I move the cursor at (or after) a period with arrow keys (or "hjkl" in vim normal mode), the goal panel remains the previous state. However, if I click on a period, or type a period, the goal view does get updated. Disabling vim extension also works, of course.

**Comment by rtetley** [comment]
This is due to the fact that the cursor movement is then triggered by a command (instead of keyboard or mouse), https://github.com/microsoft/vscode/blob/1b32ba2308db7680b0acdfbcec6e89560a4d8c45/src/vs/workbench/api/common/extHostTypes.ts#L1821.
Currently I only update the goal view if it is a keyboard or mouse event. 
I could probably relax the condition, unless someone thinks of a situation in which we wouldn't want to trigger an update when a command moves the cursor ?

**Comment by ccyip** [comment]
I think it makes sense to maintain the invariant that the cursor position and the goal view are always in sync.
