### ISSUE TITLE
Expand goals by default

### ISSUE THREAD

**Issue by rtetley** [coq-community/vscoq#647]
In collapsible goal view, all goals should be expanded by default. 
We should also add an option to switch the behaviour.

**Comment by huynhtrankhanh** [comment]
I argue that it always makes sense to show all goals. There should be no configuration option to change this. I believe we should add configuration options sparingly, as too many configuration options create extra complexity. They are also hard to discover.

It might make sense to have a "Collapse All Goals" buttons in the rare cases when the user needs to hide all goals and selectively expand some goals. How much sense this makes is debatable. Because the reality is the user can just use bullets or curly brackets to focus on a goal.

**Comment by rtetley** [comment]
Makes sense to me ! Let's forget the option then.
