### ISSUE TITLE
Error messages inside Proof View

### ISSUE THREAD

**Issue by thery** [coq-community/vscoq#73]
Some error messages wrongly go to the proof view

```
Goal True.
apply refl_equal.
```

**Comment by TheoWinterhalter** [comment]
Is this an error though? I actually like that I don't have to hover over the text that raised the error.

**Comment by thery** [comment]
yep but I like to see the goal to understand the unification problem

**Comment by thery** [comment]
I think it should go to the output window like in CoqIde

**Comment by TheoWinterhalter** [comment]
Oh, for you it overrides the goal? But yes in principle I agree we would like it in its own place.

**Comment by thery** [comment]
Not for all errors, for the example I gave, it does :disappointed:

**Comment by maximedenes** [comment]
@gares the XML protocol documentation is not completely clear to me. When does `EditAt` return an `in_r` value (i.e. a focused id)? Not sure what focused mean here.

**Comment by gares** [comment]
It is when it wants the UI to focus on the edition of a broken proof, and it gives you the boundaries. If edit_at again before the proof starts it is ok I guess, if you edit_at after the proof, in the non focus area, you are in uncharted waters since course does not do that (it adds back all the lines, hence you get the stm to unfocus)

**Comment by rtetley** [comment]
Now these messages end in the Messages section of the goal panel
